spring:
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
        show_sql: 'true'
        format_sql: 'true'
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://google/db_azship?cloudSqlInstance=azship-179211:us-central1:db-azship&socketFactory=com.google.cloud.sql.mysql.SocketFactory'
    username: 'root'
    password: '4Z5h1P#L1F77M3'
    testWhileIdle: 'true'
    validationQuery: 'SELECT 1'
  rabbitmq:
    host: 'rabbitmq'
    port: 5672
    username: 'admin'
    password: '1234'
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

entitymanager:
  packages.to.scan: 'br.com.liftt.model'

signing:
  key: 'asd4hk1h22k2asAd12ad'

security:
  oauth2:
    resource:
       userInfoUri: 'http://authservice:8081/auth/user'

flyway:
  baseline-version: 1
  check-location: 'true'
  enabled: 'true'
  locations: 'classpath:db/migration'
  sql-migration-prefix: 'V'
  sql-migration-separator: '_'
  sql-migration-suffix: '.sql'
  url: 'jdbc:mysql://google/db_azship?cloudSqlInstance=azship-179211:us-central1:db-azship&socketFactory=com.google.cloud.sql.mysql.SocketFactory'
  consumer: 'root'
  password: '4Z5h1P#L1F77M3'

logging:
  level:'INFO'
  file: 'azship.log'
