spring:
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
        show_sql: 'true'
        format_sql: 'true'
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://database:3306/db_azship?useSSL=false'
    username: 'root'
    password: 'mota'
    testWhileIdle: 'true'
    validationQuery: 'SELECT 1'
  rabbitmq:
    host: 'rabbitmq'
    port: 5672
    username: 'admin'
    password: '1234'
    listener:
      default-requeue-rejected: false
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 3
        multiplier: 1.5
        max-interval: 5000
  mail:
    host: 'smtpout.secureserver.net'
    port: 465
    username: 'ti@liftt.me'
    password: 't1L1f7#M3'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

signing:
  key: 'asd4hk1h22k2asAd12ad'

email:
  config:
    from: 'alex.mota.m@gmail.com'
    apikey: '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'

notification:
  config:
    driver:
      app_id: '83e84524-f935-4b07-aa8c-56bb2f23d7b6'
      app_auth_key: 'NzhkMGVlMTEtY2Q3OC00NGUyLTg0ZWYtNTMxM2RlNGE4YzRh'
    shipper:
      app_id: '83e84524-f935-4b07-aa8c-56bb2f23d7b6'
      app_auth_key: 'NzhkMGVlMTEtY2Q3OC00NGUyLTg0ZWYtNTMxM2RlNGE4YzRh'
    transporter:
      app_id: '83e84524-f935-4b07-aa8c-56bb2f23d7b6'
      app_auth_key: 'NzhkMGVlMTEtY2Q3OC00NGUyLTg0ZWYtNTMxM2RlNGE4YzRh'

sms:
  config:
    access_token: '1f61129054f806809d4d2375bd474520'
