spring:
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
        show_sql: 'true'
        format_sql: 'true'
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://google/db_azship?cloudSqlInstance=azship-179211:us-central1:db-azship&socketFactory=com.google.cloud.sql.mysql.SocketFactory'
    username: 'root'
    password: '4Z5h1P#L1F77M3'
    testWhileIdle: 'true'
    validationQuery: 'SELECT 1'
  rabbitmq:
    host: 'rabbitmq'
    port: 5672
    username: 'admin'
    password: '1234'
  mail:
    host: 'smtpout.secureserver.net'
    port: 465
    username: 'ti@liftt.me'
    password: 't1L1f7#M3'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

signing:
  key: 'asd4hk1h22k2asAd12ad'

sms:
  config:
    access_token: '1f61129054f806809d4d2375bd474520'
