signing:
  key: 'asd4hk1h22k2asAd12ad'

spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

feign:
  client:
    default:
      connect-timeout: 30000
      read-timeout: 30000
      logging-level: 'basic'

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

security:
  oauth2:
    resource:
       userInfoUri: 'http://authservice:8081/auth/user'

