spring:
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
        show_sql: 'true'
        format_sql: 'true'
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://google/db_azship?cloudSqlInstance=azship-179211:us-central1:db-azship&socketFactory=com.google.cloud.sql.mysql.SocketFactory'
    username: 'root'
    password: '4Z5h1P#L1F77M3'
    testWhileIdle: 'true'
    validationQuery: 'SELECT 1'

entitymanager:
  packages.to.scan: 'br.com.liftt.model'

signing:
  key: 'asd4hk1h22k2asAd12ad'
